# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
theme: jekyll-theme-minimal
title: Lover hunter
description: >- # this means to ignore newlines until "baseurl:"
  Help you to find lover.
baseurl: "/zuobin" # the subpath of the site
url: "https://kwoskywang.github.io" # the base hostname & protocol for the site
og_image: /assets/img/double-heart.jpeg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Case
    - name: Me

footer:
  show_powered_by: false
  contact:
#    - type: email
#      name: Email
#      value: yourmail@domain.com
    - type: line
      value: pang253618
      link: "#"
    - type: wechat
      value: wxid_au60bei5rzi722
      link: "#"
    - type: phone
      name: phone
      link: 0842906961
  follow:
#    - type: twitter
#      name: Twitter
#      link: http://twitter.com/YourTwitterUsername
#      username: "@YourTwitterUsername"
    - type: tiktok
      name: Tiktok
      link: https://www.tiktok.com/@userdgaggb9k89
#    - type: facebook
#      name: Facebook
#      link: http://facebook.com/juthatip104
#    - type: linkedin
#      name: LinkedIn
#      link: http://linkedin.com/in/pang253618
#    - type: github
#      name: GitHub
#      link: http://github.com/YourGitHubUsername
#    - type: dribbble
#      name: Dribbble
#      link: https://dribbble.com/YourDribbbleUsername
#    - type: rss
#      name: RSS
#      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
